name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          mkdir -p web
          echo "${{ secrets.ENV_WEB }}" > ./web/.env

          mkdir -p api
          echo "${{ secrets.ENV_API }}" > ./api/.env

      - name: Build docker images
        run: |
          docker build -t chat-db-web:latest -f web/Dockerfile .
          docker build -t chat-db-api:latest -f api/Dockerfile .

      - name: Save docker images to tarball
        run: |
          docker save -o app-images.tar chat-db-api:latest chat-db-web:latest

      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          source: "app-images.tar,docker-compose.yml,docker-compose.prod.yml,web/.env,api/.env"
          target: "~/deploy/chat-db"

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ~/deploy/chat-db

            echo "Loading docker images . . ."
            docker load -i app-images.tar

            echo "Restarting services . . ."
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --no-build --force-recreate

            rm app-images.tar

            docker image prune -f
